Entity/ContentSubjectInterface.php
<?php 
namespace TemplateDesigner\LayoutBundle\Entity;


interface ContentSubjectInterface
{

    /**
     * @return object
     */
    public function getContent();

    /**
     * @return string
     */
    public function getContentText();


}

Entity/Layout.php
<?php

namespace TemplateDesigner\LayoutBundle\Entity;

use TemplateDesigner\LayoutBundle\Model\Layout as BaseLayout;

/**
 * Layout
 */
class Layout extends BaseLayout
{
    
}

Form/LayoutType.php
<?php

namespace TemplateDesigner\LayoutBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use TemplateDesigner\LayoutBundle\Form\DataTransformer\CssClassesTransformer;

class LayoutType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        
        $routes = $options['routes'];
        $css = $options['css'];
        $tags = $options['tags'];
        $templates = $options['templates'];
        $helper = $options['helper'];
        $transformer = new CssClassesTransformer($helper);
        $builder
            
            ->add($builder->create('cssClasses','choice', array('label'=>'Layout class element','choices'=>$css,'multiple'=>true))
                 ->addModelTransformer($transformer))
            ->add('tag','choice',array('label'=>'Tag element','preferred_choices' => array('div'),'required'=>false,'empty_value'=>'Select a tag','choices'=>$tags))
            ->add('cssId',null,array('label'=>'Id element','required'=>false))
            ->add('render','choice',array('label'=>'Render','required'=>false,'empty_value'=>'Select a path','choices'=>$routes))
            ->add('include','choice',array('label'=>'Include','required'=>false,'empty_value'=>'Select a template','choices'=>$templates))
            ->add('custom',null,array('label'=>'Custom parameters','required'=>false))
            ->add('cssComplementClasses','text',array('label'=>'Additionnal class element','required'=>false))
            ->add('addNewChild','submit',array('attr'=>array('label'=>'Add a child','class'=>'btn btn-default','onclick'=>'return form_submit_add_child($(this));')))
            ->add('submit', 'submit', array('attr'=>array('class'=>'btn btn-default'),'label' => 'Update'));
        ;
         $builder->addEventListener(FormEvents::PRE_SET_DATA, function(FormEvent $event) {
            $layout = $event->getData();
            $form = $event->getForm();

            if ($layout && null === $layout->getParent() ) {
               $form->add('name',null,array('label'=>'Layout Name','required'=>true));
            }
        });
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'TemplateDesigner\LayoutBundle\Entity\Layout',
            'routes'     => null,
            'css'        => null,
            'tags'       => null,
            'templates'  => null,
            'helper'     => null,
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'templatedesigner_layoutbundle_layout';
    }
}

Controller/LayoutController.php
<?php

namespace TemplateDesigner\LayoutBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use TemplateDesigner\LayoutBundle\Entity\Layout;

/**
 * Layout controller.
 *
 * @Route("/layout")
 */
class LayoutController extends Controller
{

    /**
     * Lists all Layout entities.
     *
     * @Route("/", name="layout")
     * @Method("GET")
     */
    public function createAction()
    {
        $edit_form_twig = $this->container->getParameter('template_designer_layout.base_twig');
        $assetic = $this->container->getParameter('template_designer_layout.assetic');
        $engine = $this->container->getParameter('template_designer_layout.template_engine');
        return $this->render('TemplateDesignerLayoutBundle:Layout:create'.ucfirst($engine).'.html.twig',array('base_twig'=>$edit_form_twig,'template_assetic'=>$assetic));
    }

        /**
     * Creates a new Layout entity.
     *
     * @Route("/transform", name="layout_transform")
     */
    public function transformAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $helper = $this->get('layout.helper');
        $layout = $request->get('layout');
        $name = $request->get('name');
        $tag = $layout['tag'];
        $classes = $layout['cssClass'];
        $children = (isset($layout['children']))?$layout['children']:null;

        $root = $helper->transform($layout,$name,$classes,$tag);
        $errorList = $this->get('validator')->validate($root);
        $errors = '';
        if (count($errorList) == 0) {
            $em->flush($root);
            if($children){
               $helper->recursiveTransform($children,$root,$root);
                $i = 0;
                foreach ($root->getSubs() as $sub) {
                    $sub->setPosition(++$i);
                    $em->flush($sub);
                }  
            }
        }else{
            foreach ($errorList as $error) {
                $errors[] = $error->getMessage();
            }
        }
        return new JsonResponse($errors);
    }

    /**
     * Displays a form to edit an existing Layout entity.
     *
     * @Route("/edit", name="layout_edition")
     * @Method("GET")
     */
    public function editLayoutAction()
    {
        // instances of layout choice form and entity from config
        $config = $this->container->getParameter('template_designer_layout.class_configuration');
        $engine = $this->container->getParameter('template_designer_layout.template_engine');
        $edit_form_twig = $this->container->getParameter('template_designer_layout.base_twig');
        $assetic = $this->container->getParameter('template_designer_layout.assetic');

        $class = new \ReflectionClass($config['entity']);
        $entity = $class->newInstance();
        $formClass =  new \ReflectionClass($config['layout_choice_form']);
        $formType = $formClass->newInstance();

        $editForm = $this->createForm($formType,$entity);
        
        return $this->render('TemplateDesignerLayoutBundle:Layout:editLayout'.ucfirst($engine).'.html.twig',array(
            'entity'    => $entity,
            'edit_form' => $editForm->createView(),
            'base_twig' => $edit_form_twig,
            'template_assetic' => $assetic
            ));
    }


    /**
     * Displays a form to edit an existing Layout entity.
     *
     * @Route("/edit_ajax/", name="layout_edit")
     */
    public function editAction(Request $request)
    {
        
        if(!$request->isXmlHttpRequest()){return $this->redirect($this->generateUrl('layout_edition'));}
        $engine = $this->container->getParameter('template_designer_layout.template_engine');
        $em = $this->getDoctrine()->getManager();
        $id = $request->request->get('layout');
        $entity = $em->getRepository('TemplateDesignerLayoutBundle:Layout')->find($id);
        if (!$entity) {
                throw $this->createNotFoundException('Unable to find Layout entity.');
        }
        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('TemplateDesignerLayoutBundle:Layout:edit'.ucfirst($engine).'.html.twig',array(
            'entity'        => $entity,
            'edit_form'     => $editForm->createView(),
            'delete_form'   => $deleteForm->createView(),
            ));
    }

    /**
     * Displays a layout template of an existing Layout entity.
     *
     * @Route("/show_ajax", name="layout_show_layout")
     */
    public function showTemplateAction(Request $request)
    {
        if(!$request->isXmlHttpRequest()){return $this->redirect($this->generateUrl('layout_edition'));}
        $em = $this->getDoctrine()->getManager();
        $id = $request->request->get('root');
        $entity = $em->getRepository('TemplateDesignerLayoutBundle:Layout')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Layout entity.');
        }

        return $this->render('TemplateDesignerLayoutBundle:Layout:displayLayoutWithPositions.html.twig',array('parent'=> $entity));
    }

    /**
    * Creates a form to edit a Layout entity.
    *
    * @param Layout $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Layout $entity)
    {
        // options
        $routes = $this->get('route.manager')->getFormattedRoutesForForms();
        $templates = $this->get('template_finder')->getFormattedTemplateForForm();
        $helper = $this->get('layout.helper');
        $css = $helper->getAllCssClasses();
        $tags = $helper->getAllTags();
        // instance of layout edit form from config
        $config = $this->container->getParameter('template_designer_layout.class_configuration');
        $formClass =  new \ReflectionClass($config['layout_edit_form']);
        $formType = $formClass->newInstance();

        $form = $this->createForm($formType, $entity, array(
            'action' => $this->generateUrl('layout_update', array('id' => $entity->getId())),
            'method' => 'PUT',
            'routes' => $routes,
            'css'    => $css,
            'tags'   => $tags,
            'templates' => $templates,
            'helper'    => $helper
        ));

        return $form;
    }

    /**
     * Edits an existing Layout entity.
     *
     * @Route("/{id}", name="layout_update")
     * @Method("PUT")
     */
    public function updateAction(Request $request, Layout $entity)
    {
        $em = $this->getDoctrine()->getManager();
        $engine = $this->container->getParameter('template_designer_layout.template_engine');
        $deleteForm = $this->createDeleteForm($entity->getId());
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);
        if ($editForm->isValid()) {
            $em->flush();
        }
        return $this->render('TemplateDesignerLayoutBundle:Layout:edit'.ucfirst($engine).'.html.twig',array(
            'entity'        => $entity,
            'edit_form'     => $editForm->createView(),
            'delete_form'   => $deleteForm->createView(),
        ));
    }


    /**
     * Add child to an existing Layout entity.
     *
     * @Route("/parent/add_child", name="layout_update_add")
     */
    public function updateAddChildAction(Request $request)
    {
        if(!$request->isXmlHttpRequest()){
            return $this->redirect($this->generateUrl('layout_edition'));
        }
        $engine = $this->container->getParameter('template_designer_layout.template_engine');
        $em = $this->getDoctrine()->getManager();
        $helper = $this->get('layout.helper');
        $id = $request->request->get('parent');
        $entity = $em->getRepository('TemplateDesignerLayoutBundle:Layout')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Layout entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $newChild = $helper->addChildToEntity($entity);
        $em->flush();         

        return $this->render('TemplateDesignerLayoutBundle:Layout:edit'.ucfirst($engine).'.html.twig',array(
            'entity'        => $entity,
            'edit_form'     => $editForm->createView(),
            'delete_form'   => $deleteForm->createView(),
        ));
    }



    /**
     * Deletes a Layout entity.
     *
     * @Route("/{id}", name="layout_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, Layout $entity)
    {
        $form = $this->createDeleteForm($entity->getId());
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity->getChildren()->clear();
            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('layout_edition'));
    }

    /**
     * Creates a form to delete a Layout entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('layout_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Delete','attr'=>array('class'=>'btn btn-default')))
            ->getForm()
        ;
    }

    /**
    * @Route("/sub_layout/ajax", name="select_subs")
    */
    public function selectSubsAction(Request $request)
    {
        if(!$request->isXmlHttpRequest()){

Resources/views/Layout/createBootstrap.html.twig
{% extends base_twig %}

{% block stylesheets %}
	{{parent()}}
	{% if template_assetic is sameas(false)%}
		<link rel="stylesheet" type="text/css" href="{{asset('bundles/templatedesignerlayout/css/styleLayout.css')}}">
	{% endif %}
{% endblock %}

{% block body -%}

<div class="toolbox">
	<form class="form-inline" role="form" action="{{path('layout_transform')}}" method="#">
		<div class="form-group"><label for="name">{% trans %}Name{% endtrans %}:</label><input class="form-control" type="text" name="name"></div>
		<div class="form-group">
			<select class="form-control">
				<option value="div">{% trans %}Div{% endtrans %}</option>
				<option value="nav">{% trans %}Nav{% endtrans %}</option>
				<option value="article">{% trans %}Article{% endtrans %}</option>
				<option value="section">{% trans %}Section{% endtrans %}</option>
{# 				<option value="p">Paragraph</option> #}
			</select>
		</div>
	</form>
	<div role="alert" class="alert alert-success"></div>
	<div role="alert" class="alert alert-danger"></div>
	<ol id="selectable">
		{% for i in range (1,12)%}
			<li class="ui-state-default">{{i}}</li>
		{% endfor %}
	</ol>
	<div class="clearfix"></div>
	<div class="btns">
		<div class="btns-primary">
			<div class="btn btn-primary btn-xs" data-class="xs">{% trans %}Mobile{% endtrans %}</div>
			<div class="btn btn-primary btn-xs" data-class="sm">{% trans %}Tablet{% endtrans %}</div>
			<div class="btn btn-primary btn-xs" data-class="md">{% trans %}Desktop{% endtrans %}</div>
			<div class="btn btn-primary btn-xs" data-class="lg">{% trans %}Large Desktop{% endtrans %}</div>
		</div>
		<div class="btns-hidden">
			<div class="btn btn-primary btn-xs" data-class="xs">{% trans %}Hidden Mobile{% endtrans %}</div>
			<div class="btn btn-primary btn-xs" data-class="sm">{% trans %}Hidden Tablet{% endtrans %}</div>
			<div class="btn btn-primary btn-xs" data-class="md">{% trans %}Hidden Desktop{% endtrans %}</div>
			<div class="btn btn-primary btn-xs" data-class="lg">{% trans %}Hidden Large Desktop{% endtrans %}</div>
		</div>
		<div class="btns-visible">
			<div class="btn btn-primary btn-xs" data-class="xs">{% trans %}Only visible Mobile{% endtrans %}</div>
			<div class="btn btn-primary btn-xs" data-class="sm">{% trans %}Only visible Tablet{% endtrans %}</div>
			<div class="btn btn-primary btn-xs" data-class="md">{% trans %}Only visible Desktop{% endtrans %}</div>
			<div class="btn btn-primary btn-xs" data-class="lg">{% trans %}Only visible Large Desktop{% endtrans %}</div>
		</div>
		<div class="clearfix"></div>
	</div>

	<div class="containers clearfix">
		<div class="container-row">
			<div id="row" class="draggable">{% trans %}Row{% endtrans %}</div>
		</div>
		<div class="container-column">
			<div style="display:none;" id="col" data-class="column" class="draggable">{% trans %}Column{% endtrans %}</div>
		</div>
		{# <div class="container-container">
			<div id="container" class="draggable">container</div>
		</div> #}
	</div>
	<div data-message="{% trans %}Do you wish to confirm?{% endtrans %}" data-success="{% trans %}Layout converted{% endtrans %}" class="btn btn-success btn-transform">{% trans %}Convert{% endtrans %}</div>
</div>

<div class="root container droppable"></div>
{% endblock %}
{% block javascripts %}
{{parent()}}
{% if template_assetic is sameas(false)%}
	<script src="{{asset('bundles/templatedesignerlayout/js/jsLayout.js')}}"></script>
{% endif %}
{% endblock %}

Resources/views/Layout/displayLayoutWithPositions.html.twig
{% macro layout(parent,params,template) %}
    {% for child in parent.children %}
    	<{{child.tag}} id="{{child.cssId}}" class="{{child.cssClassesAsString}} {{child.cssComplementClasses}}">
            <div onclick="displaySubForm({layout:$(this).attr('data-id')},$('#editLayout'))" data-id="{{child.id}}" class="position">
                {{child.position}}<br>
                {% if child.custom %}
                    {{'Custom parameters: '~child.custom|trans}}
                {% elseif child.include %}
                    {{'Include: '~child.include|trans}}
                {% elseif child.render %}
                    {{'Render: '~child.render|trans}}
                {% else %}
                    &nbsp;
                {% endif %}
            </div>
            {{_self.layout(child,params,template)}}
    	</{{child.tag}}>
    {% endfor %}
{% endmacro %}


{% import _self as layout %}
<div id='root'>
    {{layout_start(parent.name,parent.position)|raw}}
    <div onclick="displaySubForm({layout:$(this).attr('data-id')},$('#editLayout'))" data-id="{{parent.id}}" class="position">{{parent.position}}</div>
    {{layout.layout(parent)}}
    {{layout_end(parent.name,parent.position)|raw}}
</div>

Resources/views/Layout/editBootstrap.html.twig
{% form_theme edit_form 'TemplateDesignerLayoutBundle:Form:common.html.twig' %}
<div class="row no-border">
	{{form_start(edit_form,{'attr':{'onsubmit':'return form_submit($(this));'}})}}
	{% for child in edit_form.children if child.vars.name == 'name' %}
		<div class="col-xs-6">
			{{form_row(child)}}
		</div>
	{% endfor %}
	{% for child in edit_form.children %}
		{% if loop.index is even %}
			<div class="col-xs-6">
				{{form_row(child)}}
			</div>
		{% else %}
			<div class="col-xs-6">
				{{form_row(child)}}
			</div>
		{% endif %}	
	{% endfor %}
	{{form_end(edit_form)}}
	<div class="col-xs-12">
		{{form(delete_form)}}
	</div>

</div>

Resources/views/Layout/editLayoutBootstrap.html.twig
{% extends base_twig %}

{% block stylesheets %}
	{{parent()}}
    {% if template_assetic is sameas(false)%}
        <link rel="stylesheet" type="text/css" href="{{asset('bundles/templatedesignerlayout/css/styleLayoutWithPosition.css')}}">
    {% endif %}
{% endblock %}

{% block body -%}
    {% form_theme edit_form 'TemplateDesignerLayoutBundle:Form:common.html.twig'%}
    <div class="container no-border">
        <div class="row no-border">
            <div class="col-xs-12 forms">
                {{form_start(edit_form,{'attr':{'role':'form','onsubmit':'return form_submit($(this));'}})}}
                {% for child in edit_form.children %}
                    {% if loop.index is even %}
                        <div class="col-xs-6">
                            {{form_row(child)}}
                        </div>
                    {% else %}
                        <div class="col-xs-6">
                            {{form_row(child)}}
                        </div>
                    {% endif %} 
                {% endfor %}
                {{form_end(edit_form)}}
            </div>
            <div class="hidden flash"></div>
            <div class="col-xs-12" id="editLayout"></div>
        </div>
    </div>

    <div id="showFullLayout"></div>
{% endblock %}

{% block javascripts %}
{{parent()}}
<script type="text/javascript">
    var urlSelectSub = '{{ path("select_subs") }}';
    var urlDisplaySubForm = '{{ path("layout_edit") }}';
    var urlDisplayTemplate = '{{ path("layout_show_layout") }}';
    var urlFormSubmitAddChild = '{{path("layout_update_add")}}';
</script>
{% if template_assetic is sameas(false)%}
    <script src="{{asset('bundles/templatedesignerlayout/js/jsLayout.js')}}"></script>
{% endif %}
{% endblock %}

Resources/views/Layout/macroLayout.html.twig
{% macro layout(parent,params,template) %}
    {% for child in parent.children %}
    	<{{child.tag}} id="{{child.cssId}}" class="{{child.cssClassesAsString}} {{child.cssComplementClasses}}">
            {# if custom => include given template in config #}
            {% if child.custom !="" %}
                {% include template %}
            {# if include without parameters #}
    		{% elseif child.include is not null %}
                {% include child.include %}
    		{% elseif child.render is not null %}
                {% render(path(child.render))%}
            {% elseif child.content is defined and child.content is not null %}
                {{child.content|raw }}
    		{% endif %}
            {{_self.layout(child,params,template)}}
    	</{{child.tag}}>
    {% endfor %}
{% endmacro %}

{% import _self as layout %}
{# if root == true, display root container #}
{% if displayRootTag is sameas(true) %}
    <{{parent.tag}} id="{{parent.cssId}}" class="{{parent.cssClassesAsString}} {{parent.cssComplementClasses}}">
{% endif %}

{{layout.layout(parent,params,template)}}

{% if displayRootTag is sameas(true) %}
    </{{parent.tag}}>
{% endif %}

Resources/views/Layout/selectSubs.html.twig
<option>{% trans %}Choose a sub layout{% endtrans %}</option>
{% for sub in subs %}
	<option value="{{sub.id}}">{{sub|trans}}</option>
{% endfor %}